import "./globals.css";
import type { Metadata } from "next";
import Header from "../components/layout/header";
import Sidebar from "../components/layout/sidebar";
import { ReactQueryProvider } from "../providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Panel",
  description: "Generated by create next app",
};

export type LayoutType = {
  hasHeader?: boolean;
  hasSidebar?: boolean;
  children: React.ReactNode;
};

export default function RootLayout({
  children,
  hasHeader = true,
  hasSidebar = true,
}: LayoutType) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className="flex flex-col w-full min-h-screen">
          {hasHeader && <Header />}

          <div className="flex flex-1 overflow-hidden">
            {hasSidebar && <Sidebar />}
            <main className="flex-1 overflow-y-auto">{children}</main>
          </div>
        </body>
      </ReactQueryProvider>
    </html>
  );
}
