import "./globals.css";
import type { Metadata } from "next";
import Header from "../components/layout/header";
import AppContainer from "../components/global/container";
import { ReactQueryProvider } from "../providers/ReactQueryProvider";
import Footer from "../components/layout/footer";

export const metadata: Metadata = {
  title: "Gym",
  description: "Generated by create next app",
};

export type LayoutType = {
  hasHeader?: boolean;
  hasSidebar?: boolean;
  children: React.ReactNode;
};

export default function RootLayout({ children, hasHeader = true }: LayoutType) {
  return (
    <html lang="en" dir="rtl">
      <body className="flex flex-col min-h-screen">
        <ReactQueryProvider>
          <AppContainer>
            {hasHeader && <Header />}
            <main>{children}</main>
            <Footer />
          </AppContainer>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
